// CREATE A CATEGORY

POST http://localhost:3000/category/new
Content-Type: application/json

{
    "title": "Lunch",
    "description": "All you can eat dishes to energize ur afternoons",
    "menuId": 2
}